# Generated by Django 4.2.2 on 2023-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangalist',
            name='name',
            field=models.CharField(choices=[('RDI', 'Reading'), ('IWR', 'I will read'), ('READ', 'Read'), ('A', 'Abandoned'), ('P', 'Postponed'), ('NI', 'Not interested')], max_length=15),
        ),
    ]
