# Generated by Django 4.2.2 on 2023-08-07 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mangalist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangalist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangalist', to=settings.AUTH_USER_MODEL),
        ),
    ]
