# Generated by Django 4.2.2 on 2023-08-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mangalist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangalist',
            name='name',
            field=models.CharField(choices=[('Reading', 'Reading'), ('I will read', 'I will read'), ('Read', 'Read'), ('Abandoned', 'Abandoned'), ('Postponed', 'Postponed'), ('Not interested', 'Not interested')], max_length=15),
        ),
    ]
