# Generated by Django 4.2.2 on 2023-06-21 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Manga', 'Manga'), ('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Comics', 'Comics'), ('Other', 'Other')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counts', models.CharField(max_length=200, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genr', models.CharField(max_length=100, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_manga', models.CharField(max_length=100, verbose_name='name_manga')),
                ('name_original', models.CharField(blank=True, max_length=100, verbose_name='name_original')),
                ('time_prod', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField(max_length=500)),
                ('avatar', models.ImageField(blank=True, default='default/none_avatar.png/', upload_to='static/images/avatars/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/products/miniava')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ManyToManyField(related_name='actors', to='manga.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='manga.categorys')),
                ('counts', models.ManyToManyField(related_name='country', to='manga.country')),
                ('genre', models.ManyToManyField(related_name='genre', to='manga.genre')),
                ('tags', models.ManyToManyField(related_name='tags', to='manga.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Glawa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('time_prod', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glaws', to='manga.manga')),
            ],
            options={
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/images/gallery/')),
                ('glawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='manga.glawa')),
            ],
        ),
    ]
