# Generated by Django 4.2.4 on 2023-08-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='total_ratings',
        ),
    ]
