# Generated by Django 4.2.2 on 2023-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='review',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=100, verbose_name='tag_name'),
        ),
    ]
