# Generated by Django 4.2.4 on 2023-08-30 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0002_remove_manga_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="time_prod",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
