# Generated by Django 4.2.2 on 2023-07-21 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_manga_review_alter_tags_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='slug',
        ),
        migrations.AddField(
            model_name='manga',
            name='decency',
            field=models.BooleanField(default=False, help_text='For adults? yes/no'),
        ),
        migrations.AddField(
            model_name='manga',
            name='english_only_field',
            field=models.CharField(blank=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
