# Generated by Django 4.2.4 on 2023-09-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0004_alter_manga_english_only_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="volume",
            field=models.IntegerField(verbose_name="volume"),
        ),
    ]
