# pyproject.toml
[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 120
lines_after_imports = 2
skip = ["__init__.py"]
skip_glob = [".venv/*"]

[tool.black]
line-length = 120
exclude = ".venv"

[tool.flake8]
exclude = ".git,__pycache__,.venv,__init__.py"
max-line-length = 120