# Generated by Django 4.2.2 on 2023-08-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangarating',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='manga.manga'),
        ),
    ]
